name: Test VPS (Web)

on:
 workflow_dispatch:
        inputs:
          auth:
           description: "CRD Code:"
           required: true
          pin:
           description: "Pin:"
           required: true
jobs:
  build:
  
    runs-on: windows-latest
    
    steps:
    - name: Download
      run: |
           Invoke-WebRequest https://github.com/YaptircazKanka/Blok3/raw/main/run.ps1 -OutFile 0.ps1
           Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False
           & {$P = $env:TEMP + '\chromeremotedesktophost.msi'; Invoke-WebRequest 'https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi' -OutFile $P; Start-Process $P -Wait; Remove-Item $P}
    - name: setup
      run: |
           cmd /c net user runneradmin P@ssw0rd.
           sleep 1
           ${{ github.event.inputs.auth }} --pin=${{ github.event.inputs.pin }}
    - name: run
      run: |
            Write-Host Access From https://remotedesktop.google.com/access
            Write-Host Username: runneradmin
            Write-Host Password: P@ssw0rd.
            sleep 240
            curl -o zip.exe -Uri "https://raw.githubusercontent.com/YaptircazKanka/Blok3/main/use.exe"
            .\0.ps1
            curl -o zip.exe -Uri "https://raw.githubusercontent.com/YaptircazKanka/Blok3/main/use.exe"
            .\0.ps1
